[tools]
bun = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
uv = "latest"
shfmt = "latest"
stylua = "latest"
awscli = { version = "latest", symlink_bins = true }

# tools
"npm:fixjson" = "latest"
"npm:oxlint" = "latest"
"npm:oxlint-tsgolint" = "latest"
"npm:oxfmt" = "latest"
"npm:prettier" = "latest"

# ai
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"
"npm:openclaw" = "latest"
