[tools]
bun = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
uv = "latest"
shfmt = "latest"
stylua = "latest"
awscli = { version = "latest", symlink_bins = true }
"npm:@openai/codex" = "latest"
"npm:prettier" = "latest"
"npm:oxlint" = "latest"
"npm:oxlint-tsgolint" = "latest"
"npm:oxfmt" = "latest"
