[tools]
bun = "latest"
node = { version = "latest", postintall = "npm i -g fixjson@latest oxlint@latest oxlint-tsgolint@latest oxfmt@latest prettier@latest @mariozechner/pi-coding-agent@latest @openai/codex@latest openclaw@latest" }
python = "latest"
ruby = "latest"
rust = "stable"
uv = "latest"
shfmt = "latest"
stylua = "latest"
awscli = { version = "latest", symlink_bins = true }
